dist: trusty
language: node_js
sudo: required
git:
  submodules: false
node_js:
  - '11.10'
services:
  - docker
cache:
  directories:
    - node_modules
before_install:
  - npm i -g yarn@latest
install:
  - yarn install
script:
  - yarn test:ci
